package sk.upjs.ics.teplakoshop;


import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author student
 */
public class HlavnyFormular extends javax.swing.JFrame {
    private TeplakyDao teplakyDao 
            = DaoFactory.INSTANCE.getTeplakyDao();

    /**
     * Creates new form HlavnyFormular
     */
    public HlavnyFormular() {
        initComponents();
        
        aktualizujZoznamTeplakov();        
    }

    private void aktualizujZoznamTeplakov() {
        List<Teplaky> zoznamTeplakov = teplakyDao.dajVsetky();
        lstTeplaky.setListData(zoznamTeplakov.toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHlavicka = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTeplaky = new javax.swing.JList();
        lblTagline = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        btnVyhladavat = new javax.swing.JButton();
        btnPridat = new javax.swing.JButton();
        btnUpravit = new javax.swing.JButton();
        btnOdstranit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHlavicka.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHlavicka.setText("Teplákošop");

        lstTeplaky.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstTeplaky.setCellRenderer(new TeplakyListCellRenderer());
        lstTeplaky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTeplakyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstTeplaky);

        lblTagline.setText("Tepláky pre každý zadok!");

        btnVyhladavat.setText("Hľadať");
        btnVyhladavat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVyhladavatActionPerformed(evt);
            }
        });

        btnPridat.setText("Pridať...");
        btnPridat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridatActionPerformed(evt);
            }
        });

        btnUpravit.setText("Upraviť...");
        btnUpravit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpravitActionPerformed(evt);
            }
        });

        btnOdstranit.setText("Odstrániť...");
        btnOdstranit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdstranitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTagline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHlavicka))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVyhladavat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPridat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpravit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOdstranit)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHlavicka)
                    .addComponent(lblTagline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVyhladavat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpravit)
                    .addComponent(btnOdstranit)
                    .addComponent(btnPridat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstTeplakyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTeplakyMouseClicked
        if(evt.getClickCount() == 2) {
            Teplaky vybrateTeplaky = (Teplaky) lstTeplaky.getSelectedValue();
        
            DetailForm detailForm = new DetailForm(vybrateTeplaky, this);
            detailForm.setVisible(true);
        }
    }//GEN-LAST:event_lstTeplakyMouseClicked

    private void btnVyhladavatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVyhladavatActionPerformed
        String filter = txtFilter.getText();
        lstTeplaky.setListData(teplakyDao.hladatPodlaFarby(filter).toArray());
    }//GEN-LAST:event_btnVyhladavatActionPerformed

    private void btnPridatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridatActionPerformed
        UpravitTeplakyForm upravitTeplakyForm = new UpravitTeplakyForm(this);
        upravitTeplakyForm.setVisible(true);
        
        aktualizujZoznamTeplakov();
    }//GEN-LAST:event_btnPridatActionPerformed

    private void btnUpravitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpravitActionPerformed
        Teplaky vybrateTeplaky = (Teplaky) lstTeplaky.getSelectedValue();
        
        UpravitTeplakyForm upravitTeplakyForm 
                = new UpravitTeplakyForm(vybrateTeplaky, this);
        upravitTeplakyForm.setVisible(true);
        
        aktualizujZoznamTeplakov();
    }//GEN-LAST:event_btnUpravitActionPerformed

    private void btnOdstranitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdstranitActionPerformed
        Teplaky vybrateTeplaky = (Teplaky) lstTeplaky.getSelectedValue();
        if(vybrateTeplaky == null) {
            return;
        }
        
        int tlacidlo = JOptionPane.showConfirmDialog(this, 
                "Naozaj odstrániť?",
                "Odstrániť tepláky",
                JOptionPane.YES_NO_OPTION
        );
        if(tlacidlo == JOptionPane.YES_OPTION) {
            teplakyDao.odstran(vybrateTeplaky);    
            aktualizujZoznamTeplakov();            
        }
    }//GEN-LAST:event_btnOdstranitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavnyFormular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavnyFormular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdstranit;
    private javax.swing.JButton btnPridat;
    private javax.swing.JButton btnUpravit;
    private javax.swing.JButton btnVyhladavat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHlavicka;
    private javax.swing.JLabel lblTagline;
    private javax.swing.JList lstTeplaky;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
